spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 585831849215-jokbgmu013ti2dqr3i30c3126ol3e6at.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
